apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace-ztunnel.yaml
- ztunnel.yaml
- podmonitor-ztunnel.yaml

patches:
- path: istio-ambient-patch.yaml
- path: istiocni-ambient-patch.yaml
- path: namespace-istio-system-patch.yaml
- path: namespace-istio-cni-patch.yaml

