apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3
type: Opaque
stringData:
  endpoint: http://minio.minio.svc.cluster.local:9000
  bucket: tempo-data
  access_key_id: minio
  access_key_secret: minio123
