apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: istio-system
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      # istio: pilot
      istio: default
  endpoints:
  - port: http-monitoring
    interval: 30s