
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  values:
    meshConfig:
      extensionProviders:
      - name: otel
        opentelemetry:
          service: otel-collector.opentelemetrycollector.svc.cluster.local
          port: 4317
      # Uncomment to enable discoverySelectors
      #discoverySelectors: 
      #- matchLabels:
      #    istio-discovery: enabled
