
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  values:
    meshConfig:
      extensionProviders:
      - name: otel
        opentelemetry:
          service: otel-collector.opentelemetrycollector.svc.cluster.local
          port: 4317
      discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
