apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-observability-operator.yaml 
- opentelemetry-product.yaml
- kiali-ossm.yaml                     
- servicemeshoperator3.yaml       
- tempo-product.yaml