apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-discovery: enabled
  name: opentelemetrycollector
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetrycollector
spec:
  config:
    exporters:
      otlp:
        endpoint: tempo-tempo-stack-distributor.tracing-system.svc.cluster.local:4317
        retry_on_failure:
          enabled: true
        sending_queue:
          enabled: true
          num_consumers: 8
          queue_size: 8000
        tls:
          insecure: true
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    service:
      pipelines:
        traces:
          exporters:
          - otlp
          processors:
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
  configVersions: 3
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  replicas: 1
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    filterStrategy: relabel-config
    prometheusCR:
      scrapeInterval: 30s
  upgradeStrategy: automatic